const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load .env if present so local builds mirror Netlify env vars
dotenv.config();

const apiBase = process.env.API_BASE_URL || '';
const target = path.join(__dirname, '..', 'env.js');

// Simple injection; API base is exposed to browser by design
const content = [
  '// Generated by scripts/inject-env.js; do not edit manually',
  'window._env_ = window._env_ || {};',
  `window._env_.API_BASE_URL = ${JSON.stringify(apiBase)};`,
  ''
].join('\n');

fs.writeFileSync(target, content, { encoding: 'utf8' });
console.log(`Wrote env.js with API_BASE_URL=${apiBase || '(empty)'}`);
